/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeValidatorRouteImport } from './routes/resume-validator'
import { Route as ImmersiveBibleRouteImport } from './routes/immersive-bible'
import { Route as IndexRouteImport } from './routes/index'

const ResumeValidatorRoute = ResumeValidatorRouteImport.update({
  id: '/resume-validator',
  path: '/resume-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmersiveBibleRoute = ImmersiveBibleRouteImport.update({
  id: '/immersive-bible',
  path: '/immersive-bible',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/immersive-bible': typeof ImmersiveBibleRoute
  '/resume-validator': typeof ResumeValidatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/immersive-bible': typeof ImmersiveBibleRoute
  '/resume-validator': typeof ResumeValidatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/immersive-bible': typeof ImmersiveBibleRoute
  '/resume-validator': typeof ResumeValidatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/immersive-bible' | '/resume-validator'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/immersive-bible' | '/resume-validator'
  id: '__root__' | '/' | '/immersive-bible' | '/resume-validator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImmersiveBibleRoute: typeof ImmersiveBibleRoute
  ResumeValidatorRoute: typeof ResumeValidatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume-validator': {
      id: '/resume-validator'
      path: '/resume-validator'
      fullPath: '/resume-validator'
      preLoaderRoute: typeof ResumeValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immersive-bible': {
      id: '/immersive-bible'
      path: '/immersive-bible'
      fullPath: '/immersive-bible'
      preLoaderRoute: typeof ImmersiveBibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImmersiveBibleRoute: ImmersiveBibleRoute,
  ResumeValidatorRoute: ResumeValidatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
